{{- if .Values.app.tls.autogenerate -}}
{{- $type := "sec" -}}
{{- $action := "tls-internal" -}}
{{- $Name := include "passbolt-library.fullname" . -}}
{{- $fullName := printf "%s-%s-%s" $Name $type $action -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "passbolt-library.labels" . | nindent 4 }}
    {{- include "passbolt-library.selectorLabels" . | nindent 4 }}
    {{- include "passbolt-library.typelabels" (dict "action" $action "type" $type) | nindent 4 }}
type: Opaque
data:
{{ ( include "passbolt.gen-internal-certs" (dict "commonName" ( printf "%s-%s-svc.cluster.local" $Name .Release.Namespace ) "altNames" nil ) ) | indent 2 }}
{{- end }}
