{{- $type := "sec" -}}
{{- $action := "tls-ingress" -}}
{{- $Name := include "passbolt-library.fullname" . -}}

{{- range $idx, $tls := .Values.ingress.tls }}
{{- if $tls.autogenerate }}
{{- $fullName := printf "%s-%s-%s-%d" $Name $type $action $idx -}}
{{- $commonName := index $tls.hosts 0 -}}
{{- $altNames := $tls.hosts -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "passbolt-library.typelabels" (dict "action" $action "type" $type) | nindent 4 }}
type: Opaque
data:
{{ ( include "passbolt.gen-ingress-certs" (dict "commonName" $commonName "altNames" $altNames ) ) | indent 2 }}
--- 
{{ end }}
{{- end }}
