name: Create Release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        name: Create Release
        run: gh release create "${GITHUB_REF#refs/*/}" -t "${GITHUB_REF#refs/*/}" --notes-file RELEASE_NOTES.md
